cast:{$[x;y]}
boolean:cast[`boolean];
char:cast[`char];
date:cast[`date];
real:cast[`real];
float:cast[`float];
guid:cast[`guid];
short:cast[`short];
int:cast[`int];
long:cast[`long];
month:cast[`month];
timespan:cast[`timespan];
timestamp:cast[`timestamp];
symbol:cast[`symbol];
time:cast[`time];
minute:cast[`minute];
second:cast[`second];
byte:cast[`byte];
datetime:cast[`datetime];
